{"uid":"2b23854ef41b88d2","name":"capmcAPISetPowerCap","fullName":"api.4-build-pipeline-only.test_set_power_cap.tavern#capmcAPISetPowerCap","historyId":"dd408b17f7b8e55258fcff9f663cd89b","time":{"start":1710836998775,"stop":1710836999047,"duration":272},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPISetPowerCap - setup1 - Get HSM Nodes","time":{"start":1710836998785,"stop":1710836998815,"duration":30},"status":"passed","steps":[],"attachments":[{"uid":"38523966f2bf7432","name":"stage_yaml","source":"38523966f2bf7432.yaml","type":"application/yaml","size":457},{"uid":"dbf194c87ea4f330","name":"rest_request","source":"dbf194c87ea4f330.yaml","type":"application/yaml","size":149},{"uid":"bfac64c899235d59","name":"rest_response","source":"bfac64c899235d59.yaml","type":"application/yaml","size":5772}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPISetPowerCap - setup2 - get_power_cap_capabilities","time":{"start":1710836998815,"stop":1710836998859,"duration":44},"status":"passed","steps":[],"attachments":[{"uid":"8f9948af803ba6a6","name":"stage_yaml","source":"8f9948af803ba6a6.yaml","type":"application/yaml","size":472},{"uid":"73f97c78dfe85cc","name":"rest_request","source":"73f97c78dfe85cc.yaml","type":"application/yaml","size":173},{"uid":"ff1e64641d179dcd","name":"rest_response","source":"ff1e64641d179dcd.yaml","type":"application/yaml","size":515}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: capmcAPISetPowerCap - setup3 - Set HSM Node 0 to Off","time":{"start":1710836998860,"stop":1710836998868,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"ceded5e70e322de6","name":"stage_yaml","source":"ceded5e70e322de6.yaml","type":"application/yaml","size":247},{"uid":"ff3525e366103375","name":"rest_request","source":"ff3525e366103375.yaml","type":"application/yaml","size":173},{"uid":"cb14f45d1fbf8995","name":"rest_response","source":"cb14f45d1fbf8995.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: capmcAPISetPowerCap - setup4 - Set HSM Node 1 to Off","time":{"start":1710836998869,"stop":1710836998877,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"a1d0b0b8c19857e3","name":"stage_yaml","source":"a1d0b0b8c19857e3.yaml","type":"application/yaml","size":247},{"uid":"fec38ada8ec4b9c7","name":"rest_request","source":"fec38ada8ec4b9c7.yaml","type":"application/yaml","size":173},{"uid":"72c37af46bf714e7","name":"rest_response","source":"72c37af46bf714e7.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: capmcAPISetPowerCap - test1 - POST set_power_cap for powered off node - failure test","time":{"start":1710836998877,"stop":1710836998892,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"cc91643d40a16c1","name":"stage_yaml","source":"cc91643d40a16c1.yaml","type":"application/yaml","size":1395},{"uid":"74f01c733f242f20","name":"rest_request","source":"74f01c733f242f20.yaml","type":"application/yaml","size":214},{"uid":"ff2de06f92f64ce8","name":"rest_response","source":"ff2de06f92f64ce8.yaml","type":"application/yaml","size":287}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 5: capmcAPISetPowerCap - setup5 - Set HSM Node 0 to Ready","time":{"start":1710836998892,"stop":1710836998900,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"c80b30fe526623db","name":"stage_yaml","source":"c80b30fe526623db.yaml","type":"application/yaml","size":251},{"uid":"b5a6d4f4eb91f1d2","name":"rest_request","source":"b5a6d4f4eb91f1d2.yaml","type":"application/yaml","size":173},{"uid":"92b30d35f516c7b","name":"rest_response","source":"92b30d35f516c7b.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 6: capmcAPISetPowerCap - setup6 - Set HSM Node 1 to Ready","time":{"start":1710836998901,"stop":1710836998911,"duration":10},"status":"passed","steps":[],"attachments":[{"uid":"ccd7a2fb590a146a","name":"stage_yaml","source":"ccd7a2fb590a146a.yaml","type":"application/yaml","size":251},{"uid":"9080b095be1c062e","name":"rest_request","source":"9080b095be1c062e.yaml","type":"application/yaml","size":173},{"uid":"f40b736ce7d1ec3e","name":"rest_response","source":"f40b736ce7d1ec3e.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 7: capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes","time":{"start":1710836998912,"stop":1710836998931,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"7dc291fbcc4a7111","name":"stage_yaml","source":"7dc291fbcc4a7111.yaml","type":"application/yaml","size":903},{"uid":"b620915c8ed03b2d","name":"rest_request","source":"b620915c8ed03b2d.yaml","type":"application/yaml","size":286},{"uid":"4f88626a3bd82c9b","name":"rest_response","source":"4f88626a3bd82c9b.yaml","type":"application/yaml","size":186}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 8: capmcAPIGetPowerCap - test3 - POST get_power_cap verify power cap values","time":{"start":1710836998932,"stop":1710836998952,"duration":20},"status":"passed","steps":[],"attachments":[{"uid":"cbb9698885197170","name":"stage_yaml","source":"cbb9698885197170.yaml","type":"application/yaml","size":2415},{"uid":"4233d8c938a07182","name":"rest_request","source":"4233d8c938a07182.yaml","type":"application/yaml","size":160},{"uid":"4f045caaab88137a","name":"rest_response","source":"4f045caaab88137a.yaml","type":"application/yaml","size":326}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 9: capmcAPISetPowerCap - test4 - POST set_power_cap value larger than max - failure test","time":{"start":1710836998953,"stop":1710836998965,"duration":12},"status":"passed","steps":[],"attachments":[{"uid":"5a604a62fae1576","name":"stage_yaml","source":"5a604a62fae1576.yaml","type":"application/yaml","size":1466},{"uid":"76c03852a6690ec6","name":"rest_request","source":"76c03852a6690ec6.yaml","type":"application/yaml","size":218},{"uid":"bfdeb22536da1239","name":"rest_response","source":"bfdeb22536da1239.yaml","type":"application/yaml","size":326}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 10: capmcAPISetPowerCap - test5 - POST set_power_cap value less than min - failure test","time":{"start":1710836998966,"stop":1710836998979,"duration":13},"status":"passed","steps":[],"attachments":[{"uid":"29028392c553e346","name":"stage_yaml","source":"29028392c553e346.yaml","type":"application/yaml","size":1449},{"uid":"fee8478418763452","name":"rest_request","source":"fee8478418763452.yaml","type":"application/yaml","size":212},{"uid":"2414741a7c188bdd","name":"rest_response","source":"2414741a7c188bdd.yaml","type":"application/yaml","size":317}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 11: capmcAPISetPowerCap - test6 - POST set_power_cap to zero","time":{"start":1710836998979,"stop":1710836998995,"duration":16},"status":"passed","steps":[],"attachments":[{"uid":"e4094372caba7658","name":"stage_yaml","source":"e4094372caba7658.yaml","type":"application/yaml","size":759},{"uid":"836541a2ef7cdb70","name":"rest_request","source":"836541a2ef7cdb70.yaml","type":"application/yaml","size":212},{"uid":"7c0ec252406d8ebf","name":"rest_response","source":"7c0ec252406d8ebf.yaml","type":"application/yaml","size":186}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 12: capmcAPISetPowerCap - test7 - POST set_power_cap to zero second time - failure test","time":{"start":1710836998996,"stop":1710836999012,"duration":16},"status":"passed","steps":[],"attachments":[{"uid":"d34fd5fe973c7ea0","name":"stage_yaml","source":"d34fd5fe973c7ea0.yaml","type":"application/yaml","size":1477},{"uid":"b57a316096346740","name":"rest_request","source":"b57a316096346740.yaml","type":"application/yaml","size":212},{"uid":"5a651d3ca93a580e","name":"rest_response","source":"5a651d3ca93a580e.yaml","type":"application/yaml","size":267}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 13: capmcAPISetPowerCap - setup7 - Set HSM Node 0 to Off","time":{"start":1710836999013,"stop":1710836999021,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"73ccb6a7d25b1d3b","name":"stage_yaml","source":"73ccb6a7d25b1d3b.yaml","type":"application/yaml","size":247},{"uid":"18cab9f60ccc7068","name":"rest_request","source":"18cab9f60ccc7068.yaml","type":"application/yaml","size":173},{"uid":"491e4ff0867d713c","name":"rest_response","source":"491e4ff0867d713c.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 14: capmcAPISetPowerCap - setup8 - Set HSM Node 0 to its original state","time":{"start":1710836999022,"stop":1710836999029,"duration":7},"status":"passed","steps":[],"attachments":[{"uid":"bf77c46ad865db4f","name":"stage_yaml","source":"bf77c46ad865db4f.yaml","type":"application/yaml","size":279},{"uid":"8831e4552abf75f9","name":"rest_request","source":"8831e4552abf75f9.yaml","type":"application/yaml","size":172},{"uid":"d27af334540c5832","name":"rest_response","source":"d27af334540c5832.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 15: capmcAPISetPowerCap - setup9 - Set HSM Node 1 to Off","time":{"start":1710836999030,"stop":1710836999038,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"718550c837a88e4","name":"stage_yaml","source":"718550c837a88e4.yaml","type":"application/yaml","size":247},{"uid":"3c8f946f075a860e","name":"rest_request","source":"3c8f946f075a860e.yaml","type":"application/yaml","size":173},{"uid":"2275c676dc7d1fd0","name":"rest_response","source":"2275c676dc7d1fd0.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 16: capmcAPISetPowerCap - setup10 - Set HSM Node 1 to its original state","time":{"start":1710836999039,"stop":1710836999047,"duration":8},"status":"passed","steps":[],"attachments":[{"uid":"3002b4f268c1809f","name":"stage_yaml","source":"3002b4f268c1809f.yaml","type":"application/yaml","size":279},{"uid":"6a2acb6b38c483b","name":"rest_request","source":"6a2acb6b38c483b.yaml","type":"application/yaml","size":172},{"uid":"5b95105ed504dc33","name":"rest_response","source":"5b95105ed504dc33.yaml","type":"application/yaml","size":134}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":17,"attachmentsCount":51,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"build-pipeline-only"},{"name":"host","value":"b8ecd9a4a728"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.4-build-pipeline-only.test_set_power_cap.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":72,"broken":0,"skipped":0,"passed":235,"unknown":0,"total":307},"items":[{"uid":"2b7e280c20356de6","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x776e3d0b35e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 1014, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}, {'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710750604529,"stop":1710750604679,"duration":150}},{"uid":"4b9a58e3a4b760ce","status":"passed","time":{"start":1710664141205,"stop":1710664141467,"duration":262}},{"uid":"60c4aa6860eb1ba7","status":"passed","time":{"start":1710577764984,"stop":1710577765241,"duration":257}},{"uid":"14f95c1d38fb4a0c","status":"passed","time":{"start":1710491330753,"stop":1710491331012,"duration":259}},{"uid":"6b4bb40cb2db2116","status":"passed","time":{"start":1710405001488,"stop":1710405001742,"duration":254}},{"uid":"3658e1313c1b654a","status":"passed","time":{"start":1710318520644,"stop":1710318520925,"duration":281}},{"uid":"2c9513a4420d5616","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fede55fc5e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1022, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1710232127169,"stop":1710232127313,"duration":144}},{"uid":"ea8497bf1e94a25f","status":"passed","time":{"start":1710145716484,"stop":1710145716757,"duration":273}},{"uid":"f10ff2168818013c","status":"passed","time":{"start":1710059383821,"stop":1710059384087,"duration":266}},{"uid":"a5d1b68c98019f7a","status":"passed","time":{"start":1709972957987,"stop":1709972958238,"duration":251}},{"uid":"4aab072ddba5e1db","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fc2a1eac5e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 1028, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}, {'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709886581731,"stop":1709886581876,"duration":145}},{"uid":"858b3980aa32d164","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f07a8b395e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 1017, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}, {'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709800146564,"stop":1709800146709,"duration":145}},{"uid":"4be6612e0ce13459","status":"passed","time":{"start":1709713808019,"stop":1709713808276,"duration":257}},{"uid":"d24a0177e71351df","status":"passed","time":{"start":1709627374835,"stop":1709627375094,"duration":259}},{"uid":"9400b264330f5272","status":"passed","time":{"start":1709541701784,"stop":1709541702045,"duration":261}},{"uid":"49bb2dee1a4a3cbf","status":"passed","time":{"start":1709454561545,"stop":1709454561807,"duration":262}},{"uid":"db5f7da0f758a76b","status":"passed","time":{"start":1709368107162,"stop":1709368107402,"duration":240}},{"uid":"e8b3a90135659a6f","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPISetPowerCap - test2 - set_power_cap for two ready nodes' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f5a07fcb4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Enum '22' does not exist. Path: '/e' Enum: [0].\n     - Value '[{'nid': 20, 'e': 22, 'err_msg': 'No NID supported controls specified'}, {'nid': 1015, 'e': 22, 'err_msg': 'Control (Node Power Limit) value (5036) is greater than maximum (925)'}]' is not of type 'none'. Path: '/nids'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1709281787717,"stop":1709281787873,"duration":156}},{"uid":"99b697fb0ed75ebd","status":"passed","time":{"start":1709195373253,"stop":1709195373521,"duration":268}},{"uid":"84a6ec0165424456","status":"passed","time":{"start":1709108924457,"stop":1709108924720,"duration":263}}]},"tags":[]},"source":"2b23854ef41b88d2.json","parameterValues":[]}