{"uid":"dde559ea10c27317","name":"capmcAPIGetXnameStatus via Redfish","fullName":"api.1-non-disruptive.test_get_xname_status.tavern#capmcAPIGetXnameStatus via Redfish","historyId":"31b0f5897a5f578325039da57cc8cc21","time":{"start":1676323431098,"stop":1676323431216,"duration":118},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)","time":{"start":1676323431106,"stop":1676323431163,"duration":57},"status":"passed","steps":[],"attachments":[{"uid":"161d187e16e40e9a","name":"stage_yaml","source":"161d187e16e40e9a.yaml","type":"application/yaml","size":478},{"uid":"d6af212a64a39fb9","name":"rest_request","source":"d6af212a64a39fb9.yaml","type":"application/yaml","size":155},{"uid":"f19691d4160c2550","name":"rest_response","source":"f19691d4160c2550.yaml","type":"application/yaml","size":974}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPIGetXnameStatusPOST - Validate response has valid fields (Redfish)","time":{"start":1676323431164,"stop":1676323431216,"duration":52},"status":"passed","steps":[],"attachments":[{"uid":"4fb825a5a5adf3ff","name":"stage_yaml","source":"4fb825a5a5adf3ff.yaml","type":"application/yaml","size":1149},{"uid":"6d4ca0a82b5b9673","name":"rest_request","source":"6d4ca0a82b5b9673.yaml","type":"application/yaml","size":155},{"uid":"1e95041cd750f547","name":"rest_response","source":"1e95041cd750f547.yaml","type":"application/yaml","size":974}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":2,"attachmentsCount":6,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"1-non-disruptive"},{"name":"host","value":"7ccdf8a649f1"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.1-non-disruptive.test_get_xname_status.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":14,"broken":0,"skipped":0,"passed":9,"unknown":0,"total":23},"items":[{"uid":"423b7b3ed8ec8f4f","status":"passed","time":{"start":1674679856655,"stop":1674679856746,"duration":91}},{"uid":"11a99a9add5dacc3","status":"passed","time":{"start":1674664397602,"stop":1674664397732,"duration":130}},{"uid":"860cab1516402ef","status":"passed","time":{"start":1674514446986,"stop":1674514447083,"duration":97}},{"uid":"9f8ddff5a8eb3bdd","status":"passed","time":{"start":1674504568282,"stop":1674504568376,"duration":94}},{"uid":"9ab4207f8e748d54","status":"passed","time":{"start":1674499162577,"stop":1674499162674,"duration":97}},{"uid":"98b10227c21a197","status":"passed","time":{"start":1674256689775,"stop":1674256689873,"duration":98}},{"uid":"6a3076c766c3b1a1","status":"passed","time":{"start":1674254090224,"stop":1674254090365,"duration":141}},{"uid":"eb1eabca1f7b3a02","status":"passed","time":{"start":1674244958308,"stop":1674244958407,"duration":99}},{"uid":"9e7583816ab3764a","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fe9114b14c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674231166058,"stop":1674231171094,"duration":5036}},{"uid":"769425d5481aa3ae","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f28145f64c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674168369557,"stop":1674168374601,"duration":5044}},{"uid":"b39e04c2ded68a5d","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7feabf5694c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674147205430,"stop":1674147210470,"duration":5040}},{"uid":"7b5406210d2c73cc","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fd8f735c4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674146065797,"stop":1674146070834,"duration":5037}},{"uid":"8d6258e50dd43e13","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fb8654944c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674145034087,"stop":1674145039126,"duration":5039}},{"uid":"810057f2544ef006","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fced46af4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674142512971,"stop":1674142518007,"duration":5036}},{"uid":"a54cc8e21acb7e4c","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fa8e59b34c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674141921836,"stop":1674141926870,"duration":5034}},{"uid":"586ca40a16508393","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f7b4b7904c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674080209552,"stop":1674080214586,"duration":5034}},{"uid":"189e0d65b8c977d2","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f8cdde404c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674074934642,"stop":1674074939686,"duration":5044}},{"uid":"50ebd15b6db53414","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f4f6161f4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674074558535,"stop":1674074563570,"duration":5035}},{"uid":"140bb45deaa6b9d8","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7ffbf00e94c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674073983250,"stop":1674073988300,"duration":5050}},{"uid":"fae28259e42f3b9b","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fd3824a44c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674072334909,"stop":1674072339961,"duration":5052}}]},"tags":[]},"source":"dde559ea10c27317.json","parameterValues":[]}